[package]
name = "api-tests"
version = "0.1.0"
authors = ["Vlady Veselinov <vladislav.veselinov@fanduel.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
testcontainers = "0.9.1"
postgres = "0.17.3"